/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.MyCart;

/**
 *
 * @author Ibrahim Saputra
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username_login = new javax.swing.JTextField();
        pass_login = new javax.swing.JPasswordField();
        Confirm_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        go_to_register = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Minimze = new javax.swing.JLabel();
        Exit_login = new javax.swing.JLabel();
        gagal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 370, 475));
        setMinimumSize(new java.awt.Dimension(360, 440));
        setUndecorated(true);
        setSize(new java.awt.Dimension(360, 440));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 230, 60, 15);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 180, 60, 15);

        username_login.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        username_login.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        username_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_loginActionPerformed(evt);
            }
        });
        getContentPane().add(username_login);
        username_login.setBounds(60, 200, 240, 20);

        pass_login.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(pass_login);
        pass_login.setBounds(60, 250, 240, 20);

        Confirm_Login.setText("Login");
        Confirm_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm_Login);
        Confirm_Login.setBounds(140, 340, 90, 30);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel1.setText("Belum punya akun?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 280, 110, 16);

        go_to_register.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        go_to_register.setText("Daftar disini");
        go_to_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go_to_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                go_to_registerMouseClicked(evt);
            }
        });
        getContentPane().add(go_to_register);
        go_to_register.setBounds(200, 280, 80, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ibrahim Saputra\\OneDrive\\Pictures\\Picsart_22-07-22_23-48-34-749.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 40, 200, 110);

        Minimze.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        Minimze.setText("-");
        Minimze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimzeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimze);
        Minimze.setBounds(310, 0, 10, 20);

        Exit_login.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Exit_login.setText("X");
        Exit_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit_loginMouseClicked(evt);
            }
        });
        getContentPane().add(Exit_login);
        Exit_login.setBounds(340, 0, 30, 30);

        gagal.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        gagal.setForeground(new java.awt.Color(255, 51, 51));
        gagal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(gagal);
        gagal.setBounds(70, 390, 230, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Picsart_22-07-22_22-59-34-795.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-40, 0, 400, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void go_to_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_go_to_registerMouseClicked
        // TODO add your handling code here:
        register rg = new register();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_go_to_registerMouseClicked

    private void username_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_loginActionPerformed

    private void MinimzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimzeMouseClicked
        // minimize di login
        this.setState(1);
    }//GEN-LAST:event_MinimzeMouseClicked

    private void Exit_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_loginMouseClicked
        // exit login
        System.exit(0);
    }//GEN-LAST:event_Exit_loginMouseClicked

    private void Confirm_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_LoginActionPerformed
        // Login
        try{
            if(register.username.equals(username_login.getText()) && register.password.equals(pass_login.getText())) {
                //Login Berhasil
                menu menu = new menu();
                menu.setVisible(true);
                menu.pack();
                menu.setLocationRelativeTo(null);
                menu.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
                this.dispose();
            }
            else {
                gagal.setText("Password atau Username Salah!!");
                }
        }catch (Exception e){
            gagal.setText("Password atau Username Salah!!");
        }
        
    }//GEN-LAST:event_Confirm_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm_Login;
    private javax.swing.JLabel Exit_login;
    private javax.swing.JLabel Minimze;
    private javax.swing.JLabel gagal;
    private javax.swing.JLabel go_to_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pass_login;
    private javax.swing.JTextField username_login;
    // End of variables declaration//GEN-END:variables
}
