/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.MyCart;

import javax.swing.JOptionPane;

/**
 *
 * @author Ibrahim Saputra
 */
public class register extends javax.swing.JFrame {

    /**
     * Variable Username Password
     */
    public static String username;
    public static String password;
    
    public register() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        reg_Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        reg_retypepass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        reg_pass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        Confirm_Register = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Label_back = new javax.swing.JLabel();
        Exit_regist = new javax.swing.JLabel();
        minimize_regist = new javax.swing.JLabel();
        Warning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 370, 475));
        setMinimumSize(new java.awt.Dimension(360, 440));
        setUndecorated(true);
        setSize(new java.awt.Dimension(360, 440));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setText("Retype Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 270, 100, 15);

        reg_Username.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(reg_Username);
        reg_Username.setBounds(70, 190, 230, 20);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 170, 60, 15);

        reg_retypepass.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(reg_retypepass);
        reg_retypepass.setBounds(70, 290, 230, 20);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 220, 60, 15);

        reg_pass.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(reg_pass);
        reg_pass.setBounds(70, 240, 230, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/100.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 30, 100, 80);

        Confirm_Register.setText("Daftar");
        Confirm_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm_Register);
        Confirm_Register.setBounds(130, 340, 90, 30);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setText("Daftar Akun");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 110, 100, 30);

        Label_back.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Label_back.setText("Back");
        Label_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_backMouseClicked(evt);
            }
        });
        getContentPane().add(Label_back);
        Label_back.setBounds(10, 10, 40, 16);

        Exit_regist.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Exit_regist.setText("X");
        Exit_regist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit_regist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit_registMouseClicked(evt);
            }
        });
        getContentPane().add(Exit_regist);
        Exit_regist.setBounds(340, 0, 30, 30);

        minimize_regist.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        minimize_regist.setText("-");
        minimize_regist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_regist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_registMouseClicked(evt);
            }
        });
        getContentPane().add(minimize_regist);
        minimize_regist.setBounds(310, 0, 10, 20);

        Warning.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Warning.setForeground(new java.awt.Color(255, 51, 51));
        Warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Warning);
        Warning.setBounds(70, 390, 230, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Picsart_22-07-22_22-59-34-795.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, 0, 400, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Label_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_backMouseClicked
        // Kembali ke menu login
        login login = new login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(register.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_Label_backMouseClicked

    private void Exit_registMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_registMouseClicked
        // exit regist
        System.exit(0);
    }//GEN-LAST:event_Exit_registMouseClicked

    private void minimize_registMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_registMouseClicked
        // minimize regis
        this.setState(1);
    }//GEN-LAST:event_minimize_registMouseClicked

    private void Confirm_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_RegisterActionPerformed
        // Pendaftaran
        if(reg_pass.getText().equals(reg_retypepass.getText())){
            username = reg_Username.getText();
            password = reg_pass.getText();
            
            //pop up
            JOptionPane.showMessageDialog(null, "Akun Anda Berhasil Terdaftar!!");
            
            //go to login
            login login = new login();
            login.setVisible(true);
            login.pack();
            login.setLocationRelativeTo(null);
            login.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
            this.dispose();
        }
        else {
            Warning.setText("Password Tidak Cocok!!");
        }
    }//GEN-LAST:event_Confirm_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm_Register;
    private javax.swing.JLabel Exit_regist;
    private javax.swing.JLabel Label_back;
    private javax.swing.JLabel Warning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel minimize_regist;
    private javax.swing.JTextField reg_Username;
    private javax.swing.JPasswordField reg_pass;
    private javax.swing.JPasswordField reg_retypepass;
    // End of variables declaration//GEN-END:variables
}
